Peridigm link fails in the following way.  I think its because the static variable in Field.h has not been initialized.
Need find that.  Things are looking pretty good otherwise.

static const std::map<string, FieldSpec> Map;

CMakeFiles/Peridigm.dir/Peridigm_OutputManager_VTK_XML.cpp.o: In function `std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, Field_NS::FieldSpec, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Field_NS::FieldSpec> > >::find(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/usr/lib/gcc/x86_64-redhat-linux/4.5.1/../../../../include/c++/4.5.1/bits/stl_map.h:712: undefined reference to `Field_NS::FieldSpecMap::Map'
collect2: ld returned 1 exit status
make[2]: *** [src/Peridigm] Error 1






git-svn-id: svn+ssh://software.sandia.gov/svn/private/peridigm/trunk@861 d9297710-12f9-482b-b11f-fb677dc88bbb